# Generated by Django 4.0.7 on 2022-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_rename_email_message_email_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, choices=[('Tablets', 'Tablets'), ('Capsules', 'Capsules'), ('Suspension', 'Suspension'), ('Surgical', 'Surgical'), ('Suppository', 'Suppository'), ('Pessary', 'Pessary'), ('Ampule', 'Ampule'), ('Vial', 'Vial'), ('Pen set', 'Pen set'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
