# Generated by Django 4.0.7 on 2022-09-03 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_customers_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
    ]
