# Generated by Django 4.0.7 on 2022-09-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_customers_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='dashboard.customer'),
        ),
    ]
