# Generated by Django 4.0.7 on 2022-09-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_order_customers_order_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
    ]
