# Generated by Django 4.0.7 on 2022-09-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_customer_date_added_customer_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='dashboard.customer'),
        ),
    ]
