# Generated by Django 4.0.7 on 2022-09-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_orderitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='user',
        ),
    ]
