# Generated by Django 4.0.7 on 2022-09-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_customer_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mcaz_license',
            field=models.CharField(blank=True, help_text='MCAZ License Number', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Tablets', 'Tablets'), ('Capsules', 'Capsules'), ('Suspension', 'Suspension'), ('Surgical', 'Surgical'), ('Suppository', 'Suppository'), ('Pessary', 'Pessary'), ('Ampule', 'Ampule'), ('Vial', 'Vial'), ('Pen set', 'Pen set'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
