# Generated by Django 4.0.7 on 2022-09-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='email_to',
        ),
    ]
