# Generated by Django 4.0.7 on 2022-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_user_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_paid',
            field=models.BooleanField(default=False),
        ),
    ]
