# Generated by Django 4.0.7 on 2022-09-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_orderitem_customer_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
