# Generated by Django 4.0.7 on 2022-09-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_vendor_order_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
