# Generated by Django 4.0.7 on 2022-09-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_budget'),
        ('dashboard', '0027_rename_customer_order_user_remove_orderitem_customer'),
    ]

    operations = [
    ]
